// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtMUGIeuA1z3vhO0bVDdx4WaJ6hwXVDk',
    appId: '1:496320293166:web:82c11dd2d6e97571e432bf',
    messagingSenderId: '496320293166',
    projectId: 'studymate-web',
    authDomain: 'studymate-web.firebaseapp.com',
    storageBucket: 'studymate-web.appspot.com',
    measurementId: 'G-VV5Z4D1ESN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJg-IXxa7FKiv1wO0jSYHyih3QeknzFU0',
    appId: '1:496320293166:android:b718f8a9c0228ae1e432bf',
    messagingSenderId: '496320293166',
    projectId: 'studymate-web',
    storageBucket: 'studymate-web.appspot.com',
  );
}
